### ISSUE TITLE
tab size

### ISSUE THREAD

**Issue by rimmesbe** [slimdagreat/prj-rev-bwfs-dasmoto#1]
Generally tabs are set to 2 spaces or 4. This is a little extreme.

https://github.com/slimdagreat/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html

**Comment by slimdagreat** [comment]
Dreameaver tab size was set at 4. Not sure why it seemed like more. I have changed the value of tab size to 2.

**Comment by rimmesbe** [comment]
hmm interesting, Looks like 12 spaces on github
